stages:
  preprocess:
    cmd: python src/preprocess_data.py
    deps:
    - src/preprocess_data.py
    -  data/raw/raw_dataset.csv
  train:
    cmd: python .\src\train.py
    deps:
    - .\src\train.py
  test:
    cmd: python .\src\test.py
    deps:
    - .\src\test.py